import type { PopupConfig, TriggerConfig, PopupType } from "./defaults"
import {
    DEFAULT_COUNTDOWN_CONFIG,
    DEFAULT_CONTENT_LOCKER_CONFIG,
    DEFAULT_SPIN_WHEEL_CONFIG,
    DEFAULT_MULTI_STEP_CONFIG,
} from "./defaults"

const defaultAdvancedFeatures = {
    countdown: { ...DEFAULT_COUNTDOWN_CONFIG },
    contentLocker: { ...DEFAULT_CONTENT_LOCKER_CONFIG },
    spinWheel: { ...DEFAULT_SPIN_WHEEL_CONFIG },
    multiStep: { ...DEFAULT_MULTI_STEP_CONFIG },
} as const

export interface PopupTemplate {
    id: string
    name: string
    category: string
    description: string
    preview: string
    popupType: PopupType
    triggerConfig: TriggerConfig[]
    popupConfig: PopupConfig
}

export const POPUP_TEMPLATES: PopupTemplate[] = [
    {
        id: "newsletter-signup",
        name: "Newsletter Signup",
        category: "Lead Capture",
        description: "Clean email capture with compelling copy. Perfect for blogs and content sites.",
        preview: "N",
        popupType: "modal",
        triggerConfig: [
            { type: "time-delay", enabled: true, config: { seconds: 8 } },
            { type: "scroll", enabled: false, config: { percentage: 50 } },
            { type: "exit-intent", enabled: true, config: { sensitivity: 20 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: false, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "modal",
            headline: "Stay in the loop!",
            body: "Get the latest articles, tips, and exclusive content delivered to your inbox every week. No spam, unsubscribe anytime.",
            ctaText: "Subscribe",
            backgroundColor: "#ffffff",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#1f2937",
            buttonColor: "#3b82f6",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "x",
            borderRadius: 12,
            shadowIntensity: 3,
            maxWidth: 460,
            customCss: "",
            successMessage: "You're in! Check your inbox to confirm.",
            redirectUrl: "",
            formFields: [
                { id: "email", type: "email", label: "Email", placeholder: "your@email.com", required: true },
            ],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "discount-code",
        name: "Discount Code",
        category: "E-Commerce",
        description: "Urgency-driven offer with discount code reveal. Reduces cart abandonment.",
        preview: "D",
        popupType: "modal",
        triggerConfig: [
            { type: "time-delay", enabled: false, config: { seconds: 5 } },
            { type: "scroll", enabled: false, config: { percentage: 50 } },
            { type: "exit-intent", enabled: true, config: { sensitivity: 15 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: false, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "modal",
            headline: "Wait! Here's 15% off",
            body: "We noticed you're leaving. Use code SAVE15 at checkout for 15% off your entire order. Limited time only.",
            ctaText: "Reveal My Code",
            backgroundColor: "#fef3c7",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#92400e",
            buttonColor: "#f59e0b",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "x",
            borderRadius: 12,
            shadowIntensity: 4,
            maxWidth: 440,
            customCss: "",
            successMessage: "Your code: SAVE15 -- Use it at checkout!",
            redirectUrl: "",
            formFields: [
                { id: "email", type: "email", label: "Email", placeholder: "your@email.com", required: true },
            ],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "announcement",
        name: "Announcement",
        category: "Marketing",
        description: "Product launch or feature update announcement. Non-intrusive slide-in.",
        preview: "A",
        popupType: "slide-in",
        triggerConfig: [
            { type: "time-delay", enabled: true, config: { seconds: 3 } },
            { type: "scroll", enabled: false, config: { percentage: 50 } },
            { type: "exit-intent", enabled: false, config: { sensitivity: 20 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: false, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "slide-in",
            headline: "Introducing Dark Mode",
            body: "Our most requested feature is here. Try the new dark mode experience today.",
            ctaText: "Try It Now",
            backgroundColor: "#1f2937",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#f9fafb",
            buttonColor: "#10b981",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "x",
            borderRadius: 12,
            shadowIntensity: 4,
            maxWidth: 360,
            customCss: "",
            successMessage: "",
            redirectUrl: "",
            formFields: [],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "social-proof",
        name: "Social Proof",
        category: "Marketing",
        description: "\"X people viewing\" notification toast. Builds urgency and trust.",
        preview: "S",
        popupType: "toast",
        triggerConfig: [
            { type: "time-delay", enabled: true, config: { seconds: 4 } },
            { type: "scroll", enabled: false, config: { percentage: 50 } },
            { type: "exit-intent", enabled: false, config: { sensitivity: 20 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: false, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "toast",
            headline: "42 people are viewing this right now",
            body: "Join 10,000+ happy customers who chose us this month.",
            ctaText: "Shop Now",
            backgroundColor: "#ffffff",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#111827",
            buttonColor: "#059669",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "x",
            borderRadius: 10,
            shadowIntensity: 3,
            maxWidth: 340,
            customCss: "",
            successMessage: "",
            redirectUrl: "",
            formFields: [],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "countdown-timer",
        name: "Countdown Timer",
        category: "E-Commerce",
        description: "Time-limited offer with urgency. Great for flash sales and product launches.",
        preview: "C",
        popupType: "modal",
        triggerConfig: [
            { type: "time-delay", enabled: true, config: { seconds: 5 } },
            { type: "scroll", enabled: false, config: { percentage: 50 } },
            { type: "exit-intent", enabled: false, config: { sensitivity: 20 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: false, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "modal",
            headline: "Flash Sale Ends Soon!",
            body: "Get 30% off everything for the next 24 hours. Don't miss this deal.",
            ctaText: "Claim 30% Off",
            backgroundColor: "#1e1b4b",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#e0e7ff",
            buttonColor: "#ef4444",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "x",
            borderRadius: 16,
            shadowIntensity: 5,
            maxWidth: 480,
            customCss: "",
            successMessage: "Your discount has been applied!",
            redirectUrl: "",
            formFields: [
                { id: "email", type: "email", label: "Email", placeholder: "your@email.com", required: true },
            ],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "feedback-survey",
        name: "Feedback Survey",
        category: "Engagement",
        description: "Quick rating and feedback collection. Slide-in format for minimal disruption.",
        preview: "F",
        popupType: "slide-in",
        triggerConfig: [
            { type: "time-delay", enabled: false, config: { seconds: 5 } },
            { type: "scroll", enabled: true, config: { percentage: 70 } },
            { type: "exit-intent", enabled: true, config: { sensitivity: 20 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: false, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "slide-in",
            headline: "Quick question",
            body: "How would you rate your experience today? Your feedback helps us improve.",
            ctaText: "Share Feedback",
            backgroundColor: "#ffffff",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#374151",
            buttonColor: "#6366f1",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "x",
            borderRadius: 12,
            shadowIntensity: 3,
            maxWidth: 360,
            customCss: "",
            successMessage: "Thank you for your feedback!",
            redirectUrl: "",
            formFields: [
                { id: "email", type: "email", label: "Email", placeholder: "your@email.com", required: false },
                { id: "feedback", type: "custom", label: "Feedback", placeholder: "What can we improve?", required: true },
            ],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "lead-magnet",
        name: "Lead Magnet",
        category: "Lead Capture",
        description: "Gated content download. Offer a free PDF, ebook, or resource for an email.",
        preview: "L",
        popupType: "modal",
        triggerConfig: [
            { type: "time-delay", enabled: true, config: { seconds: 10 } },
            { type: "scroll", enabled: true, config: { percentage: 40 } },
            { type: "exit-intent", enabled: false, config: { sensitivity: 20 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: false, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "modal",
            headline: "Free Guide: 10 Growth Hacks",
            body: "Download our proven playbook that helped 500+ businesses grow their revenue by 3x. Completely free.",
            ctaText: "Download Now",
            backgroundColor: "#eff6ff",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#1e3a5f",
            buttonColor: "#2563eb",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "x",
            borderRadius: 12,
            shadowIntensity: 3,
            maxWidth: 480,
            customCss: "",
            successMessage: "Check your email for the download link!",
            redirectUrl: "",
            formFields: [
                { id: "name", type: "name", label: "Name", placeholder: "Your name", required: true },
                { id: "email", type: "email", label: "Email", placeholder: "your@email.com", required: true },
            ],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "webinar-registration",
        name: "Webinar Registration",
        category: "Events",
        description: "Event signup with urgency and social proof. Captures name and email.",
        preview: "W",
        popupType: "modal",
        triggerConfig: [
            { type: "time-delay", enabled: true, config: { seconds: 15 } },
            { type: "scroll", enabled: false, config: { percentage: 50 } },
            { type: "exit-intent", enabled: false, config: { sensitivity: 20 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: false, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "modal",
            headline: "Live Webinar This Thursday",
            body: "Join 2,000+ marketers learning how to double conversions. Limited spots available. Register now for free.",
            ctaText: "Reserve My Spot",
            backgroundColor: "#f5f3ff",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#4c1d95",
            buttonColor: "#7c3aed",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "x",
            borderRadius: 12,
            shadowIntensity: 3,
            maxWidth: 480,
            customCss: "",
            successMessage: "You're registered! Check your email for the link.",
            redirectUrl: "",
            formFields: [
                { id: "name", type: "name", label: "Name", placeholder: "Your name", required: true },
                { id: "email", type: "email", label: "Email", placeholder: "your@email.com", required: true },
            ],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "cookie-wall",
        name: "Cookie Wall",
        category: "Compliance",
        description: "Full consent required before accessing site. GDPR/CCPA compliant overlay.",
        preview: "K",
        popupType: "fullscreen",
        triggerConfig: [
            { type: "time-delay", enabled: false, config: { seconds: 5 } },
            { type: "scroll", enabled: false, config: { percentage: 50 } },
            { type: "exit-intent", enabled: false, config: { sensitivity: 20 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: true, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "fullscreen",
            headline: "We value your privacy",
            body: "This website uses cookies to enhance your browsing experience, serve personalized content, and analyze our traffic. By clicking \"Accept All\", you consent to our use of cookies.",
            ctaText: "Accept All",
            backgroundColor: "#ffffff",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#374151",
            buttonColor: "#3b82f6",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "none",
            borderRadius: 16,
            shadowIntensity: 5,
            maxWidth: 560,
            customCss: "",
            successMessage: "",
            redirectUrl: "",
            formFields: [],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "age-verification",
        name: "Age Verification",
        category: "Compliance",
        description: "18+ age gate for age-restricted content or products.",
        preview: "V",
        popupType: "fullscreen",
        triggerConfig: [
            { type: "time-delay", enabled: false, config: { seconds: 5 } },
            { type: "scroll", enabled: false, config: { percentage: 50 } },
            { type: "exit-intent", enabled: false, config: { sensitivity: 20 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: true, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "fullscreen",
            headline: "Are you 18 or older?",
            body: "You must be of legal drinking age to enter this site. By clicking 'Yes, I am 18+' you confirm you are of legal age.",
            ctaText: "Yes, I am 18+",
            backgroundColor: "#111827",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#f9fafb",
            buttonColor: "#ef4444",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "none",
            borderRadius: 16,
            shadowIntensity: 5,
            maxWidth: 480,
            customCss: "",
            successMessage: "",
            redirectUrl: "",
            formFields: [],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "exit-offer",
        name: "Exit Offer",
        category: "E-Commerce",
        description: "Last-chance discount for visitors about to leave. Maximum conversion recovery.",
        preview: "E",
        popupType: "modal",
        triggerConfig: [
            { type: "time-delay", enabled: false, config: { seconds: 5 } },
            { type: "scroll", enabled: false, config: { percentage: 50 } },
            { type: "exit-intent", enabled: true, config: { sensitivity: 10 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: false, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "modal",
            headline: "Forgot something?",
            body: "Your cart is waiting! Complete your order now and get free shipping. This offer expires in 30 minutes.",
            ctaText: "Complete My Order",
            backgroundColor: "#ffffff",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#111827",
            buttonColor: "#ef4444",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "x",
            borderRadius: 12,
            shadowIntensity: 4,
            maxWidth: 460,
            customCss: "",
            successMessage: "Redirecting to checkout...",
            redirectUrl: "",
            formFields: [],
            ...defaultAdvancedFeatures,
        },
    },
    {
        id: "welcome-back",
        name: "Welcome Back",
        category: "Engagement",
        description: "Greet returning visitors with a personalized message and offer.",
        preview: "B",
        popupType: "toast",
        triggerConfig: [
            { type: "time-delay", enabled: true, config: { seconds: 2 } },
            { type: "scroll", enabled: false, config: { percentage: 50 } },
            { type: "exit-intent", enabled: false, config: { sensitivity: 20 } },
            { type: "click", enabled: false, config: { selector: "" } },
            { type: "page-load", enabled: false, config: {} },
            { type: "inactivity", enabled: false, config: { seconds: 30 } },
        ],
        popupConfig: {
            popupType: "toast",
            headline: "Welcome back!",
            body: "We missed you. Here's 10% off your next purchase as a thank you for coming back.",
            ctaText: "Claim Offer",
            backgroundColor: "#ecfdf5",
            backgroundImage: "",
            backgroundGradient: "",
            textColor: "#065f46",
            buttonColor: "#059669",
            buttonTextColor: "#ffffff",
            imageUrl: "",
            closeButtonStyle: "x",
            borderRadius: 10,
            shadowIntensity: 3,
            maxWidth: 340,
            customCss: "",
            successMessage: "Your code: WELCOME10",
            redirectUrl: "",
            formFields: [],
            ...defaultAdvancedFeatures,
        },
    },
]

export function getTemplateById(id: string): PopupTemplate | undefined {
    return POPUP_TEMPLATES.find((t) => t.id === id)
}

export function getTemplatesByCategory(): Record<string, PopupTemplate[]> {
    const grouped: Record<string, PopupTemplate[]> = {}
    for (const template of POPUP_TEMPLATES) {
        if (!grouped[template.category]) {
            grouped[template.category] = []
        }
        grouped[template.category].push(template)
    }
    return grouped
}
